### ISSUE TITLE
to_task function

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/nomad-material-processing#102]
I was implementing the MBE use case and we realized we needed the sources as referenced entries and not nested sub_sections.

This would lead the to_task function to fail because it doesn't find source.material (it is now source.reference.material)

Should be make to_task accept also referecnes @hampusnasstrom ?

**Comment by hampusnasstrom** [comment]
@aalbino2, I think we should still have a nested source object which caries the instance data of the source in the deposition. Such as the temperature as a function of process time. What we discussed with Oliver was to have an additional entity for the whole instrument which would contain the "static" information of the source such as model, manufacturer, etc. This static data is also step independent I guess. In the filling of the instance data there could then be certain things which are filled by default from the instrument description. What do you think?

**Comment by hampusnasstrom** [comment]
Anyways, the material should not be static but can I guess change from deposition to deposition. Unless you are referring to the crucible with the material in which case I think that can be the material reference.

**Comment by aalbino2** [comment]
Yeah, there are several viable ways that look all equally good.

I would in any case create a separate entry for the instrument with stable metadata such as chamber geometry, etc.

The metadata such as Temperature vs time can be placed in a nested section or in an entry, with not much substantial difference. I will try to stick to what we have now to avoid causing mess, though

**Comment by hampusnasstrom** [comment]
By "I will try to stick to what we have now" do you mean the composed section as it is in the `VaporDepostion` data model?

**Comment by aalbino2** [comment]
exactly
