### ISSUE TITLE
molar amount missing in solution

### ISSUE THREAD

**Issue by schumannj** [FAIRmat-NFDI/nomad-material-processing#125]
I cannot find a quantity to store the molar amount I add to a solution. Maybe I missed it. If not, I think it would be a good quantity to add. I have examples where the user mentions the amount in mol of a solute in the experimental section. @ka-sarthak

**Comment by ka-sarthak** [comment]
You are right, this is not available as a quantity. However, the information is available in the normalization. The number of moles is calculated from the `mass` as an intermediate step to compute the molar concentrations. In additional, we can have the functionality where the user adds the moles: this triggers the calculation of mass. 

Do you suggest we have `moles` as a quantity in `SolutionComponent`?

**Comment by ka-sarthak** [comment]
@schumannj Sounds great, I pick it up next week
