### ISSUE TITLE
some details in Vapor Deposition

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/nomad-material-processing#38]
There are a couple of things in our classes I would like to bring on discussion again:
- Substrate -> ThinFilmStack -> Substrate. the Substrate name used for different things is a bit confusing. It's also difficult to find another name. Let'S see
- vapor_flow_rate, we set it as a molar_flow_rate. I would like to call the composed object molar_flow_rate. If in PLD then someone wants it called "vapor flow rate", we can use a label for it

What do you think @hampusnasstrom ? Let's discuss this in one of next data modeling meetings

**Comment by hampusnasstrom** [comment]
Let's discuss it on Wednesday!
