### ISSUE TITLE
Add sample class

### ISSUE THREAD

**Issue by ka-sarthak** [FAIRmat-NFDI/nomad-material-processing#81]
The need for a `Sample` class emerges when multiple samples are cut from a bulk material, each treated as a separate entity. These samples have the same material system but can have different geometry and sample IDs assigned.

The `Sample` class should allow the reuse of a material system (a composite system itself) for multiple sample entries via reference. 

`Sample` also inherits composite system, and reference to its material system is made in the `components` using a `SystemComponent`.
```py
Sample(CompositeSystem):
  geometry = Geometry
  components = list[SystemComponent(reference=CompositeSystem)]
```

**Comment by hampusnasstrom** [comment]
I think `CompositeSystem` is already the class you are looking for.

**Comment by ka-sarthak** [comment]
I summarized our discussions from today in the PR: https://github.com/FAIRmat-NFDI/nomad-material-processing/pull/82#issuecomment-2348370542
