### ISSUE TITLE
Install via pip fails with current version

### ISSUE THREAD

**Issue by fabianschoeppach** [FAIRmat-NFDI/nomad-material-processing#84]
Hi,  
I tried to install nomad-materials-processing with `pip` and it fails.  
I also tried this in a fresh python3.9 and python3.12 env, same result. 

```bash
> python -m venv .pyenv # or python3.9 -m venv .pyenv
> source .pyenv/bin/activate 
> pip install nomad-materials-processing
ERROR: Could not find a version that satisfies the requirement nomad-materials-processing (from versions: none)
ERROR: No matching distribution found for nomad-materials-processing
```

Can someone please verify this on their system?

**Comment by hampusnasstrom** [comment]
This was broken by this commit by @ka-sarthak which needed a version of nomad-lab not yet published to PyPI: https://github.com/FAIRmat-NFDI/nomad-material-processing/commit/03d7dcec5151100cce2833a81f86a9e73540b93e#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711
For now you can either install version 0.0.10 by:
```sh
pip install nomad-material-processing==0.0.10
```
Or by using the gitlab registry for the latest nomad-lab version
```sh
pip install nomad-material-processing --index-url https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple
```

**Comment by hampusnasstrom** [comment]
I guess we should add a note to the README for now @ka-sarthak
